#pragma once

#include "ImGui.h"

namespace
{
    struct WindUpDefaultSystemColorScheme { const char *name; ImGuiCol index; };

    constexpr std::array color_table{
        WindUpDefaultSystemColorScheme{"Text",                       ImGuiCol_Text},
        WindUpDefaultSystemColorScheme{"TextDisabled",               ImGuiCol_TextDisabled},
        WindUpDefaultSystemColorScheme{"WindowBg",                   ImGuiCol_WindowBg},
        WindUpDefaultSystemColorScheme{"ChildBg",                    ImGuiCol_ChildBg},
        WindUpDefaultSystemColorScheme{"PopupBg",                    ImGuiCol_PopupBg},
        WindUpDefaultSystemColorScheme{"Border",                     ImGuiCol_Border},
        WindUpDefaultSystemColorScheme{"BorderShadow",               ImGuiCol_BorderShadow},
        WindUpDefaultSystemColorScheme{"FrameBg",                    ImGuiCol_FrameBg},
        WindUpDefaultSystemColorScheme{"FrameBgHovered",             ImGuiCol_FrameBgHovered},
        WindUpDefaultSystemColorScheme{"FrameBgActive",              ImGuiCol_FrameBgActive},
        WindUpDefaultSystemColorScheme{"TitleBg",                    ImGuiCol_TitleBg},
        WindUpDefaultSystemColorScheme{"TitleBgActive",              ImGuiCol_TitleBgActive},
        WindUpDefaultSystemColorScheme{"TitleBgCollapsed",           ImGuiCol_TitleBgCollapsed},
        WindUpDefaultSystemColorScheme{"MenuBarBg",                  ImGuiCol_MenuBarBg},
        WindUpDefaultSystemColorScheme{"ScrollbarBg",                ImGuiCol_ScrollbarBg},
        WindUpDefaultSystemColorScheme{"ScrollbarGrab",              ImGuiCol_ScrollbarGrab},
        WindUpDefaultSystemColorScheme{"ScrollbarGrabHovered",       ImGuiCol_ScrollbarGrabHovered},
        WindUpDefaultSystemColorScheme{"ScrollbarGrabActive",        ImGuiCol_ScrollbarGrabActive},
        WindUpDefaultSystemColorScheme{"CheckMark",                  ImGuiCol_CheckMark},
        WindUpDefaultSystemColorScheme{"SliderGrab",                 ImGuiCol_SliderGrab},
        WindUpDefaultSystemColorScheme{"SliderGrabActive",           ImGuiCol_SliderGrabActive},
        WindUpDefaultSystemColorScheme{"Button",                     ImGuiCol_Button},
        WindUpDefaultSystemColorScheme{"ButtonHovered",              ImGuiCol_ButtonHovered},
        WindUpDefaultSystemColorScheme{"ButtonActive",               ImGuiCol_ButtonActive},
        WindUpDefaultSystemColorScheme{"Header",                     ImGuiCol_Header},
        WindUpDefaultSystemColorScheme{"HeaderHovered",              ImGuiCol_HeaderHovered},
        WindUpDefaultSystemColorScheme{"HeaderActive",               ImGuiCol_HeaderActive},
        WindUpDefaultSystemColorScheme{"Separator",                  ImGuiCol_Separator},
        WindUpDefaultSystemColorScheme{"SeparatorHovered",           ImGuiCol_SeparatorHovered},
        WindUpDefaultSystemColorScheme{"SeparatorActive",            ImGuiCol_SeparatorActive},
        WindUpDefaultSystemColorScheme{"ResizeGrip",                 ImGuiCol_ResizeGrip},
        WindUpDefaultSystemColorScheme{"ResizeGripHovered",          ImGuiCol_ResizeGripHovered},
        WindUpDefaultSystemColorScheme{"ResizeGripActive",           ImGuiCol_ResizeGripActive},
        WindUpDefaultSystemColorScheme{"InputTextCursor",            ImGuiCol_InputTextCursor},
        WindUpDefaultSystemColorScheme{"TabHovered",                 ImGuiCol_TabHovered},
        WindUpDefaultSystemColorScheme{"Tab",                        ImGuiCol_Tab},
        WindUpDefaultSystemColorScheme{"TabSelected",                ImGuiCol_TabSelected},
        WindUpDefaultSystemColorScheme{"TabSelectedOverline",        ImGuiCol_TabSelectedOverline},
        WindUpDefaultSystemColorScheme{"TabDimmed",                  ImGuiCol_TabDimmed},
        WindUpDefaultSystemColorScheme{"TabDimmedSelected",          ImGuiCol_TabDimmedSelected},
        WindUpDefaultSystemColorScheme{"TabDimmedSelectedOverline",  ImGuiCol_TabDimmedSelectedOverline},
        WindUpDefaultSystemColorScheme{"PlotLines",                  ImGuiCol_PlotLines},
        WindUpDefaultSystemColorScheme{"PlotLinesHovered",           ImGuiCol_PlotLinesHovered},
        WindUpDefaultSystemColorScheme{"PlotHistogram",              ImGuiCol_PlotHistogram},
        WindUpDefaultSystemColorScheme{"PlotHistogramHovered",       ImGuiCol_PlotHistogramHovered},
        WindUpDefaultSystemColorScheme{"TableHeaderBg",              ImGuiCol_TableHeaderBg},
        WindUpDefaultSystemColorScheme{"TableBorderStrong",          ImGuiCol_TableBorderStrong},
        WindUpDefaultSystemColorScheme{"TableBorderLight",           ImGuiCol_TableBorderLight},
        WindUpDefaultSystemColorScheme{"TableRowBg",                 ImGuiCol_TableRowBg},
        WindUpDefaultSystemColorScheme{"TableRowBgAlt",              ImGuiCol_TableRowBgAlt},
        WindUpDefaultSystemColorScheme{"TextLink",                   ImGuiCol_TextLink},
        WindUpDefaultSystemColorScheme{"TextSelectedBg",             ImGuiCol_TextSelectedBg},
        WindUpDefaultSystemColorScheme{"TreeLines",                  ImGuiCol_TreeLines},
        WindUpDefaultSystemColorScheme{"DragDropTarget",             ImGuiCol_DragDropTarget},
        WindUpDefaultSystemColorScheme{"DragDropTargetBg",           ImGuiCol_DragDropTargetBg},
        WindUpDefaultSystemColorScheme{"UnsavedMarker",              ImGuiCol_UnsavedMarker},
        WindUpDefaultSystemColorScheme{"NavCursor",                  ImGuiCol_NavCursor},
        WindUpDefaultSystemColorScheme{"NavWindowingHighlight",      ImGuiCol_NavWindowingHighlight},
        WindUpDefaultSystemColorScheme{"NavWindowingDimBg",          ImGuiCol_NavWindowingDimBg},
        WindUpDefaultSystemColorScheme{"ModalWindowDimBg",           ImGuiCol_ModalWindowDimBg},
    };
}